### ISSUE TITLE
Missing attribute `load_power`

### ISSUE THREAD

**Issue by cxlwill** [syssi/xiaomi_airconditioningcompanion#10]
Home Assistant 0.65.4 with `miio` 0.3.8

```
2018-03-13 12:52:48 ERROR (MainThread) [homeassistant.components.climate] xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 235, in async_update
    ATTR_LOAD_POWER: state.load_power,
AttributeError: 'AirConditioningCompanionStatus' object has no attribute 'load_power'
```

**Comment by blindlight86** [comment]
the same with 0.65.3

**Comment by syssi** [comment]
The property is available in python-miio 0.3.8 for sure. HA 0.65.3 doesn't include the library yet. It will be part of HA 0.66. Please check you are using python-miio for real.

**Comment by cxlwill** [comment]
You are right. I thought the latest version all ready met with `miio` 0.3.8. So I upgrade miio library, modify other `miio` relevant devices' requirement and clean component's cache. I'm pretty sure that it used 0.3.8 for real this time. But new attribute error came:

```
Log Details (ERROR)
xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 230, in async_update
    ATTR_AIR_CONDITION_POWER: state.air_condition_power,
AttributeError: 'AirConditioningCompanionStatus' object has no attribute 'air_condition_power'
``` 

That's strange because I notice that this attribute is defined correctly. And I do have AC's plug in with power data existed.

**Comment by syssi** [comment]
I updated the component. The issue should be gone now.
