### ISSUE TITLE
Problem with setting temperature

### ISSUE THREAD

**Issue by MadZeliboba** [syssi/xiaomi_airconditioningcompanion#107]
This is the log:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 265, in _try_command
    result = yield from self.hass.async_add_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/miio/airconditioningcompanion.py", line 461, in send_configuration
    return self.send_command(configuration)
  File "/usr/local/lib/python3.7/site-packages/miio/airconditioningcompanion.py", line 402, in send_command
    return self.send("send_cmd", [str(command)])
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 124, in send
    return self._protocol.send(command, parameters, retry_count)
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 196, in send
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -4, 'message': '(null)'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 428, in async_set_temperature
    yield from self._send_configuration()
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 493, in _send_configuration
    Led.Off,
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 271, in _try_command
    _LOGGER.error(mask_error, exc)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 181, in emit
    record, stack, _figure_out_source(record, stack, self.hass)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 97, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by syssi** [comment]
Which AC model do you own? Could you update the custom component and try again?
