### ISSUE TITLE
error message in home-assistant 0.66

### ISSUE THREAD

**Issue by KangKai1982** [syssi/xiaomi_airconditioningcompanion#11]
Home-assistant 0.66 release
python-miio updated to 0.39

config:

```
- platform: xiaomi_miio
      name: mi_acpartner
      host: 192.168.1.107
      token: 53dxxxxxxxxxxxxxxxxxxxx
      target_sensor: sensor.temperature_xxxxxxxxxxxx
      scan_interval: 60
```
error log message:

```
xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/config/custom_components/climate/xiaomi_miio.py", line 206, in async_update
    ATTR_SWING_MODE: state.swing_mode.name,
AttributeError: 'bool' object has no attribute 'name'
```

**Comment by syssi** [comment]
I will care about the issue tonight.

**Comment by syssi** [comment]
It looks like you aren't using python-miio 0.3.9. In version 0.3.8 the state.swing_mode was an boolean. In version 0.3.9 it's an enum now. Please check your installation.

**Comment by KangKai1982** [comment]
I checked the python-miio version and it shows:

```
# pip show python-miio
Name: python-miio
Version: 0.3.9
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu Rytilahti
Author-email: tpr@iki.fi
License: GPLv3
Location: /usr/local/lib/python3.6/site-packages
Requires: android-backup, attrs, construct, pretty-cron, tqdm, click, appdirs, zeroconf, cryptography, pytz
```

**Comment by syssi** [comment]
Could you check your `/config/deps/` folder for an old python-miio version? It still looks like you have multiple python-miio versions installed.

**Comment by KangKai1982** [comment]
Just checked that folder, you are right, the python-miio version 0.3.8 is laying there.
thank you.
