### ISSUE TITLE
Error on HA 0.66

### ISSUE THREAD

**Issue by liorm0505** [syssi/xiaomi_airconditioningcompanion#12]
Hi, 

upgraded to HA 0.66 and i get the following error:

```
xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/config/custom_components/climate/xiaomi_miio.py", line 205, in async_update
    ATTR_TEMPERATURE: state.temperature,
AttributeError: 'AirConditioningCompanionStatus' object has no attribute 'temperature'
```

My configuration:

```
climate:
  - platform: xiaomi_miio
    name: Aqara Air Conditioning Companion
    host: 192.168.x.xx
    token: aefec50f7xxxxxxxxxxxxxxxxxxx
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60
```
I do not have a sensor connected to my Air Condition companion.

**Comment by syssi** [comment]
Please update the custom component and use the latest version of the develop branch:

https://github.com/syssi/xiaomi_airconditioningcompanion/archive/develop.zip

**Comment by ntcong** [comment]
isn't that in https://github.com/rytilahti/python-miio/commit/5d874155ea2dbae9ae17e86fd58e466e44d1a6b8#diff-f3dc2005ebf7fddbea7c921f3bcce1f5 temperature was renamed to target_temperature?

**Comment by nutinshell** [comment]
> Please update the custom component and use the latest version of the develop branch:
> 
> https://github.com/syssi/xiaomi_airconditioningcompanion/archive/develop.zip

still same error, any idea?

**Comment by syssi** [comment]
It was my fault. I missed a piece of code. :-)

@liorm0505 You must provide a target_sensor for the room temperature. Without this sensor the loop isn't closed and the thermostat cannot work.

**Comment by nutinshell** [comment]
hmm, comes new error like:

```ERROR:homeassistant.components.climate:xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/var/opt/homeassistant/custom_components/climate/xiaomi_miio.py", line 205, in async_update
    ATTR_SWING_MODE: state.swing_mode.name,
  File "/var/opt/homeassistant/deps/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 126, in swing_mode
    return SwingMode(mode)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid SwingMode
INFO:homeassistant.core:Bus:Handling <Event system_log_event[L]: level=ERROR, exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/var/opt/homeassistant/custom_components/climate/xiaomi_miio.py", line 205, in async_update
    ATTR_SWING_MODE: state.swing_mode.name,
  File "/var/opt/homeassistant/deps/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 126, in swing_mode
    return SwingMode(mode)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid SwingMode
, timestamp=1522652863.6614914, message=xiaomi_miio: Error on device update!, source=deps/lib/python3.5/site-packages/miio/airconditioningcompanion.py>```

**Comment by syssi** [comment]
This is a new discovery. I thought the swing mode can be just on and off. It looks like your device supports additional swing modes. Could you describe the swing modes of your AC and the meaning of the current setting ("2")? Thanks in advance!
