### ISSUE TITLE
ValueError: 2 is not a valid SwingMode

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_airconditioningcompanion#13]
```
INFO:homeassistant.core:Bus:Handling <Event system_log_event[L]: level=ERROR, exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/var/opt/homeassistant/custom_components/climate/xiaomi_miio.py", line 205, in async_update
    ATTR_SWING_MODE: state.swing_mode.name,
  File "/var/opt/homeassistant/deps/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 126, in swing_mode
    return SwingMode(mode)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid SwingMode
, timestamp=1522652863.6614914, message=xiaomi_miio: Error on device update!, source=deps/lib/python3.5/site-packages/miio/airconditioningcompanion.py>
```

@nutinshell I think I have an idea what's going on. The format of the `state` property depends on the hardware version of the acpartner. :-( Could you provide the output of some 

```
mirobo --ip <ip> --token <token> raw_command get_state_and_mode '[]'
```

calls? The output of

```
mirobo --ip <ip> --token <token> -d info
```

would be interesting, too.

**Comment by syssi** [comment]
@nutinshell Could you help here and provide some details?

**Comment by nutinshell** [comment]
@syssi sorry didn't notice this.

first command result:
```
Sending cmd get_state_and_mode with params []
Error: {'code': -32601, 'message': 'Method not found.'}
```
second:

```INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Connecting to 10.85.85.67 with token *token*
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container: 
    data = Container: 
        length = 0
        offset2 = 32
        value = b'' (total 0)
        data = b'' (total 0)
        offset1 = 32
    header = Container: 
        length = 16
        offset2 = 16
        value = Container: 
            length = 32
            unknown = 0
            device_id = b'\x03F\xfaG' (total 4)
            ts = 1970-01-04 04:12:33
        data = b'!1\x00 \x00\x00\x00\x00\x03F\xfaG\x00\x04/\xb1' (total 16)
        offset1 = 0
    checksum = b'\xb9\x11\xa1\x90\x83\xe0\x06\x9f{\xfa\xc0S\x14\x9b\x96\xc7' (total 16)
DEBUG:miio.device:Discovered 0346fa47 with ts: 1970-01-04 04:12:33, token: b'*token*'
DEBUG:miio.device:10.85.85.67:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:10.85.85.67:54321 (ts: 1970-01-04 04:12:33, id: 1) << {'id': 1, 'result': {'mac': '28:6C:07:aa:bb:cc', 'fw_ver': '1.4.1_146', 'netif': {'localIp': '10.85.85.67', 'gw_mac': '00:0C:29:aa:bb:cc', 'mask': '255.255.0.0', 'gw': '10.85.0.85'}, 'model': 'lumi.acpartner.v1', 'ot': 'otu', 'cfg_time': 0, 'otu_stat': [43, 42, 2161, 12, 2136, 8], 'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM', 'mmfree': 169616, 'ap': {'rssi': -44, 'ssid': 'Voyager', 'bssid': '38:ED:18:cc:dd:ee'}, 'token': '*token*', 'hw_ver': 'MW300', 'ott_stat': [2, 6, 30, 58], 'mcu_fw_ver': '0143', 'life': 274353}}
lumi.acpartner.v1 v1.4.1_146 (28:6C:07:cc:dd:ff) @ 10.85.85.67 - token: *token*
DEBUG:miio.vacuum_cli:Full response: {'ap': {'bssid': '38:ED:18:11:22:33',
        'rssi': -44,
        'ssid': 'Voyager'},
 'cfg_time': 0,
 'fw_ver': '1.4.1_146',
 'hw_ver': 'MW300',
 'life': 274353,
 'mac': '28:6C:07:cc:dd:ee',
 'mcu_fw_ver': '0143',
 'mmfree': 169616,
 'model': 'lumi.acpartner.v1',
 'netif': {'gw': '10.85.0.85',
           'gw_mac': '00:0C:29:aa:cc:dd',
           'localIp': '10.85.85.67',
           'mask': '255.255.0.0'},
 'ot': 'otu',
 'ott_stat': [2, 6, 30, 58],
 'otu_stat': [43, 42, 2161, 12, 2136, 8],
 'token': '*token*',
 'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM'}
DEBUG:miio.vacuum_cli:Writing {'seq': 1, 'manual_seq': 0} to /root/.cache/python-miio/python-mirobo.seq```

**Comment by syssi** [comment]
@nutinshell Sorry, there was a typo. The correct command is:

```
mirobo --ip <ip> --token <token> raw_command get_model_and_state '[]'
```

Please provide the output. :-)

**Comment by nutinshell** [comment]
> Please provide the output. :-)

```Sending cmd get_model_and_state with params []
['010502020000258701', '010101170100002587', '0']```

**Comment by syssi** [comment]
python-miio can handle a SwingMode "2" now.
