### ISSUE TITLE
xiaomi_miio_airconditioningcompanion: Error on device update!

### ISSUE THREAD

**Issue by ten-ltw** [syssi/xiaomi_airconditioningcompanion#135]
Model ID: lumi.acpartner.mcn04

I think is should support lumi.acpartner.mcn04 right?
My firmware version is 2.2.0.0022.

And I also get an Error: Error doing job: Task exception was never retrieved.

I'm not sure what can I do now.

```
xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 347, in async_update
    state = yield from self.hass.async_add_job(self._device.status)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/airconditioningcompanion.py", line 265, in status
    return AirConditioningCompanionStatus(dict(model_and_state=status))
  File "/usr/local/lib/python3.9/site-packages/miio/airconditioningcompanion.py", line 103, in __init__
    self.state = data["model_and_state"][1]
IndexError: list index out of range
```

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 295, in _async_sensor_changed
    self._async_update_temp(new_state)
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 274, in _async_update_temp
    self._current_temperature = self.hass.config.units.temperature(
AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by syssi** [comment]
The `lumi.acpartner.mcn04` isn' supported unfortunately.

**Comment by ten-ltw** [comment]
Sadly to hear that.

**Comment by ten-ltw** [comment]
closed
