### ISSUE TITLE
Support for KTBL04LM 

### ISSUE THREAD

**Issue by johnjoemorgan** [syssi/xiaomi_airconditioningcompanion#139]
Is support for KTBL04LM in the pipeline?

**Comment by brightlike** [comment]
agree

**Comment by songjingcn** [comment]
some errors:  

model: KTBL04LM
os: Core 2023.12.3
Frontend 20231208.2
System: Ubuntu 22.04

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:575
Integration: climate (documentation, issues)
First occurred: 15:21:09 (1 occurrences)
Last logged: 15:21:09

xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 350, in async_update
    state = await self.hass.async_add_job(self._device.status)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/miio/airconditioningcompanion.py", line 264, in status
    return AirConditioningCompanionStatus(dict(model_and_state=status))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/miio/airconditioningcompanion.py", line 103, in __init__
    self.state = data["model_and_state"][1]
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
