### ISSUE TITLE
 TEMP_CELSIUS was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues

### ISSUE THREAD

**Issue by hoanglongutc** [syssi/xiaomi_airconditioningcompanion#165]
Hi,
I'm getting an error when upgrading Hass version 2024.2.2. 
```

TEMP_CELSIUS was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues

```

Looking forward to receiving your support. Thanks
![image](https://github.com/syssi/xiaomi_airconditioningcompanion/assets/35026043/fb6f2b71-3aca-49b1-9b05-406bbf3e942a)

**Comment by RatheeM** [comment]
I have the same problem

**Comment by klu16** [comment]
I think this is somewhat similar and related. I got a following error:

    Entity None (<class 'custom_components.xiaomi_miio_airconditioningcompanion.climate.XiaomiAirConditioningCompanion'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|SWING_MODE: 41>, please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by NLfrans** [comment]
Can you please look in to this?

```
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 20:10:41 (1 occurrences)
Last logged: 20:10:41

TEMP_CELSIUS was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
```

```
Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:197
integration: Climate (documentation, issues)
First occurred: 20:10:41 (9 occurrences)
Last logged: 20:10:41

HVAC_MODE_HEAT was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
HVAC_MODE_OFF was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
SUPPORT_FAN_MODE was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
SUPPORT_SWING_MODE was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
SUPPORT_TARGET_TEMPERATURE was used from xiaomi_miio_airconditioningcompanion, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'xiaomi_miio_airconditioningcompanion' custom integration
```

**Comment by syssi** [comment]
@NLfrans I've pushed some changes and prepared a new release. Please give it a try!

**Comment by NLfrans** [comment]
> @NLfrans I've pushed some changes and prepared a new release. Please give it a try!

Thank you looking in to it

but there are new warnings

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:370
integration: Climate (documentation, issues)
First occurred: 08:25:49 (3 occurrences)
Last logged: 08:25:49

Entity None (<class 'custom_components.xiaomi_miio_airconditioningcompanion.climate.XiaomiAirConditioningCompanion'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues
Entity None (<class 'custom_components.xiaomi_miio_airconditioningcompanion.climate.XiaomiAirConditioningCompanion'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues
Entity None (<class 'custom_components.xiaomi_miio_airconditioningcompanion.climate.XiaomiAirConditioningCompanion'>) implements HVACMode(s): heat, cool, auto, dry, fan_only, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues
```
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 08:25:49 (3 occurrences)
Last logged: 08:25:51

Detected that custom integration 'xiaomi_miio_airconditioningcompanion' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/xiaomi_miio_airconditioningcompanion/climate.py, line 258: async_track_state_change(hass, sensor_entity_id, self._async_sensor_changed), please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues
Detected that custom integration 'xiaomi_miio_airconditioningcompanion' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/xiaomi_miio_airconditioningcompanion/climate.py, line 347: state = await self.hass.async_add_job(self._device.status), please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues
```

```
 Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 08:25:49 (2 occurrences)
Last logged: 08:25:50

Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'xiaomi_miio_airconditioningcompanion' at custom_components/xiaomi_miio_airconditioningcompanion/climate.py, line 129: from miio import AirConditioningCompanion, DeviceException (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 680: return os.listdir(self.root or '.')), please create a bug report at https://github.com/syssi/xiaomi_airconditioningcompanion/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component result = await task File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 155, in async_setup await component.async_setup(config) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 148, in async_setup self.hass.async_create_task_internal( File "/usr/src/homeassistant/homeassistant/core.py", line 830, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 318, in async_setup_platform await self._platforms[key].async_setup(platform_config, discovery_info) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_setup await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 129, in async_setup_platform from miio import AirConditioningCompanion, DeviceException 
```
