### ISSUE TITLE
Missing external temp display on the card

### ISSUE THREAD

**Issue by klu16** [syssi/xiaomi_airconditioningcompanion#172]
Hi syssi,

before the update to 2024.8.1.1, there was a possibility to display a room temp from an external sensor.

I mean this part of the config:

climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion
    host: 192.168.1.xx
    token: <token>
    **target_sensor: sensor.aqara_temperature_humidity_sensor_temperature**
    scan_interval: 2

Now I see a following errors in the log:

```
Logger: homeassistant.helpers.event
Source: helpers/event.py:327
First occurred: 03:27:08 (4 occurrences)
Last logged: 03:33:28

Error while dispatching event for sensor.aqara_temperature_humidity_sensor_temperature to <Job track state_changed event ['sensor.aqara_temperature_humidity_sensor_temperature'] HassJobType.Coroutinefunction <bound method XiaomiAirConditioningCompanion._async_sensor_changed of <entity climate.aqara_air_conditioning_companion=off>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 327, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 950, in async_run_hass_job
    return self._async_add_hass_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 758, in _async_add_hass_job
    hassjob.target(*args), name=hassjob.name, loop=self.loop
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: XiaomiAirConditioningCompanion._async_sensor_changed() missing 2 required positional arguments: 'old_state' and 'new_state'
```

Could you please fix this? Thanks :)

**Comment by klu16** [comment]
Any update on this, please? :)

**Comment by levanLuongnt** [comment]
Me too!

**Comment by zsqduke** [comment]
Need this!

**Comment by sample** [comment]
Same problem

**Comment by I-G-1-1** [comment]
Same problem here.
The integration doesn't recognize anymore the "target_sensor" so the entity has "**current_temperature: null**" as attribute.

```
hvac_modes: heat, cool, auto, dry, fan_only, off
min_temp: 18
max_temp: 30
target_temp_step: 1
fan_modes: low, medium, high, auto
swing_modes: on, off, unknown2, unknown7, chigoon, chigooff
current_temperature: null #<-- here is the issue
temperature: 20
fan_mode: high
swing_mode: on
ac_model: XXXRedactedXXX
load_power: 2
hvac_mode: off
led: false
friendly_name: Aqara Air Conditioning Companion
supported_features: 425
```

**Comment by JamesLiang23** [comment]
The issue is caused by the change of the callback signature from async_track_state_change to async_track_state_change_event, it's a easy fix.

I submitted a PR and it's waiting for approval for merging, see #176 

For those who wish to apply the changes to your local copy, please refer to the PR and make changes to your local copy to solve the issue.

**Comment by klu16** [comment]
> The issue is caused by the change of the callback signature from async_track_state_change to async_track_state_change_event, it's a easy fix.
> 
> I submitted a PR and it's waiting for approval for merging, see [#176](https://github.com/syssi/xiaomi_airconditioningcompanion/pull/176)
> 
> For those who wish to apply the changes to your local copy, please refer to the PR and make changes to your local copy to solve the issue.

Thank you, I have manually updated climate.py and I confirm it works now!

**Comment by syssi** [comment]
Fixed by #176
