### ISSUE TITLE
Update fails with ValueError: invalid literal for int() with base 10: 'A'

### ISSUE THREAD

**Issue by thundergreen** [syssi/xiaomi_airconditioningcompanion#18]
2018-05-08 12:13:31 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.aqara_air_conditioning_companion fails
Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/hass/.homeassistant/custom_components/climate/xiaomi_miio.py", line 212, in async_update
    ATTR_LED: state.led,
  File "/home/hass/homeassistant/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 106, in led
    return 'on' if (int(self.data[1][8:9]) == Led.On.value) else 'off'
ValueError: invalid literal for int() with base 10: 'A'

**Comment by syssi** [comment]
Will be fixed with the next release of python-miio by https://github.com/rytilahti/python-miio/pull/315.

**Comment by thundergreen** [comment]
fixed with workaround. Waiting python-mio
