### ISSUE TITLE
Bug with Home Assistant 0.69.1  version 

### ISSUE THREAD

**Issue by ZealiGit** [syssi/xiaomi_airconditioningcompanion#21]
### 1
Update for climate.xiaomi_air_conditioner fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 212, in async_update
    ATTR_LED: state.led,
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 106, in led
    return 'on' if (int(self.data[1][8:9]) == Led.On.value) else 'off'
ValueError: invalid literal for int() with base 10: 'A'

### 2

Error executing service <ServiceCall climate.set_temperature: entity_id=['climate.xiaomi_air_conditioner'], temperature=26.0>

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1002, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 332, in async_temperature_set_service
    await climate.async_set_temperature(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 324, in async_set_temperature
    yield from self._send_configuration()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 366, in _send_configuration
    OperationMode[self._current_operation],
  File "/usr/lib/python3.5/enum.py", line 277, in __getitem__
    return cls._member_map_[name]
KeyError: 'cool'

**Comment by wolfit50** [comment]
so when will python-miio v0.4.0 come to release?

**Comment by syssi** [comment]
I hope next weekend. You could installiert the current master branch by `pip3 install master.zip` in the meantime. Don't forget to start bin/hass with `--skip-pip`.
