### ISSUE TITLE
Update for climate.aqara_air_conditioning_companion fails

### ISSUE THREAD

**Issue by neykovt** [syssi/xiaomi_airconditioningcompanion#23]
HI, 
got some error when try to change values.
`Update for climate.aqara_air_conditioning_companion fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 212, in async_update
    ATTR_LED: state.led,
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 106, in led
    def air_condition_model(self) -> bytes:
ValueError: invalid literal for int() with base 10: 'A'`

**Comment by neykovt** [comment]
0.70.1 (virtual python env installation)

**Comment by syssi** [comment]
HA 0.72 is required!
