### ISSUE TITLE
homeassistant 0.72,python-miio 0.4.0 ,got error.

### ISSUE THREAD

**Issue by happylichuanxi** [syssi/xiaomi_airconditioningcompanion#26]
Thanks for your great job,recently I update the new homeassistant version and got an error when i control the airconditon:
Error executing service <ServiceCall climate.set_temperature: temperature=24.0, entity_id=['climate.ac1']>
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 339, in async_temperature_set_service
    await climate.async_set_temperature(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 324, in async_set_temperature
    yield from self._send_configuration()
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 370, in _send_configuration
    Led.Off,
  File "/home/homeassistant/.homeassistant/custom_components/climate/xiaomi_miio.py", line 165, in _try_command
    partial(func, *args, **kwargs))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 395, in send_configuration
    configuration = configuration.replace('[tt]', format(target_temperature, 'X'))
ValueError: Unknown format code 'X' for object of type 'float'

**Comment by syssi** [comment]
Fixed by https://github.com/syssi/xiaomi_airconditioningcompanion/commit/2debfc83ab0a2a76513fbaa70213c9c08bc2d966
