### ISSUE TITLE
There is an error，homeassistant==0.69.1，and xiaomi_airconditioningcompanion Latest commit 04f8640

### ISSUE THREAD

**Issue by youqingkui** [syssi/xiaomi_airconditioningcompanion#27]
2018-07-07 12:37:12 INFO (MainThread) [homeassistant.components.climate] Setting up climate.xiaomi_miio
2018-07-07 12:37:12 INFO (MainThread) [custom_components.climate.xiaomi_miio] Initializing with host lumi-acpartner-v3_miio78476440 (token d8154...)
2018-07-07 12:37:12 INFO (MainThread) [custom_components.climate.xiaomi_miio] lumi.acpartner.v3 1.4.1_150 MW300 detected
2018-07-07 12:37:12 ERROR (MainThread) [custom_components.climate.xiaomi_miio] name:空调伴侣, device:<miio.airconditioningcompanion.AirConditioningCompanion object at 0x110b83748>, unique_id:lumi.acpartner.v3-78:11:DC:B2:A0:3E, sensor_entity_id:sensor.temperature_158d00020ef39b, min_temp:16, max_temp:30
2018-07-07 12:37:12 ERROR (MainThread) [custom_components.climate.xiaomi_miio] Got new state: <AirConditioningCompanionStatus power=on, load_power=24, air_condition_model=010500978022222102, led=off, target_temperature=26, swing_mode=SwingMode.On, fan_speed=FanSpeed.Auto, mode=OperationMode.Ventilate>
2018-07-07 12:37:12 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 301, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: climate.

**Comment by sdc6882278** [comment]
my environment ： homeassistant==0.69.1，python-miio==0.4.0, also encounter this error。

**Comment by syssi** [comment]
Please change the name of the device. Don't use chinese characters as entity name.

cp. https://github.com/syssi/xiaomi_airconditioningcompanion/issues/30
