### ISSUE TITLE
ValueError: 7 is not a valid SwingMode

### ISSUE THREAD

**Issue by yangliang2016** [syssi/xiaomi_airconditioningcompanion#43]
xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/root/.homeassistant/custom_components/climate/xiaomi_miio.py", line 270, in async_update
    ATTR_SWING_MODE: state.swing_mode.name,
  File "/root/.homeassistant/deps/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 215, in swing_mode
    return SwingMode(mode)
  File "/usr/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 7 is not a valid SwingMode

**Comment by syssi** [comment]
Do you aware of any special swing modes of your AC?

**Comment by yangliang2016** [comment]
it is ok, display Unknown7. thank you!

**Comment by syssi** [comment]
Do you know the meaning of the setting? Are you able to change the swing mode by the MiHome app? Which swing modes are available?
