### ISSUE TITLE
Error while setting up platform xiaomi_miio_airconditioningcompanion

### ISSUE THREAD

**Issue by TinyFatty** [syssi/xiaomi_airconditioningcompanion#60]
Already installed python-miio but still can't find the module.Here's error message.
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 97, in async_setup_platform
    from miio import AirConditioningCompanion, DeviceException
ImportError: No module named 'miio'

**Comment by TinyFatty** [comment]
Seems that HA must be >=0.91 to work

**Comment by syssi** [comment]
Correct.
