### ISSUE TITLE
The new version is no longer available

### ISSUE THREAD

**Issue by unpack8866** [syssi/xiaomi_airconditioningcompanion#64]
The new version is no longer available

**Comment by syssi** [comment]
Could you provide a screenshot? Where do you see this message?

**Comment by leo369258** [comment]
Testing configuration at /config
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up introduction
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up http
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setup of domain introduction took 0.0 seconds.
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up api
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up history
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up frontend
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up group
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up discovery
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up map
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate.py", line 17, in <module>
    from homeassistant.components.climate.const import (
ModuleNotFoundError: No module named 'homeassistant.components.climate.const'
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.xiaomi_miio_airconditioningcompanion. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate.py", line 17, in <module>
    from homeassistant.components.climate.const import (
ModuleNotFoundError: No module named 'homeassistant.components.climate.const'
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Unable to find component climate.xiaomi_miio_airconditioningcompanion
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up climate
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain discovery took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up conversation
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up logbook
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up config
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up script
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up light
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
Failed config
  General Errors: 
    - Platform not found: climate.xiaomi_miio_airconditioningcompanion

Successful config (partial)

**Comment by unpack8866** [comment]
> 你能提供截图吗？你在哪里看到这条消息？

![N6GA85S_5VHRWY0XFCYO}DM](https://user-images.githubusercontent.com/40196105/60090069-63549980-9774-11e9-9fca-2e1419fabadd.png)

**Comment by unpack8866** [comment]
> Could you provide a screenshot? Where do you see this message?

![N6GA85S_5VHRWY0XFCYO}DM](https://user-images.githubusercontent.com/40196105/60090138-88490c80-9774-11e9-97cc-f7b8a6935180.png)

**Comment by unpack8866** [comment]
Current Version 0.94.4

**Comment by unpack8866** [comment]
> Could you provide a screenshot? Where do you see this message?

![WEL$UJS@U5@75HYEE14 U31](https://user-images.githubusercontent.com/40196105/60090344-f261b180-9774-11e9-9cf4-ec24bca8392a.png)

**Comment by syssi** [comment]
Should be fixed by #69.
