### ISSUE TITLE
The new version is no longer available

### ISSUE THREAD

**Issue by leo369258** [syssi/xiaomi_airconditioningcompanion#65]
Testing configuration at /config
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up introduction
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up http
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setup of domain introduction took 0.0 seconds.
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-06-25 10:37:36 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up api
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up history
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up frontend
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up group
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up discovery
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up map
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate.py", line 17, in <module>
    from homeassistant.components.climate.const import (
ModuleNotFoundError: No module named 'homeassistant.components.climate.const'
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.xiaomi_miio_airconditioningcompanion. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate.py", line 17, in <module>
    from homeassistant.components.climate.const import (
ModuleNotFoundError: No module named 'homeassistant.components.climate.const'
2019-06-25 10:37:37 ERROR (MainThread) [homeassistant.loader] Unable to find component climate.xiaomi_miio_airconditioningcompanion
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up climate
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain discovery took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.1 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up conversation
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up logbook
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up config
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up script
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up light
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.0 seconds.
2019-06-25 10:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
Failed config
  General Errors: 
    - Platform not found: climate.xiaomi_miio_airconditioningcompanion

Successful config (partial)

**Comment by leo369258** [comment]
home assistant version 0.62.1

**Comment by leo369258** [comment]
climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion
    host: 192.168.50.84
    token: XXXXXXXXXXXXXXXXXXXXXXX
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60

**Comment by leo369258** [comment]
/volume1/docker/homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py
/volume1/docker/homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/__init__.py

**Comment by syssi** [comment]
Should be fixed by #69.
